1、对比表和word
--查询word中的名称在表t_flow_meeting_cmteeman是否存在
with t as (
select '夏锦良' as doc_name from dual union all
select '袁玉平' as doc_name from dual union all
select '蔡晓斌' as doc_name from dual union all
select '陈全' as doc_name from dual union all
select '陈微微' as doc_name from dual union all
select '陈霖' as doc_name from dual union all
select '方任斌' as doc_name from dual union all
select '傅玉凤' as doc_name from dual union all
select '郭丽华' as doc_name from dual union all
select '顾文佳' as doc_name from dual union all
select '惠淼枫' as doc_name from dual union all
select '何希婧' as doc_name from dual union all
select '黄实彪' as doc_name from dual union all
select '黄文雯' as doc_name from dual union all
select '贾晓斌' as doc_name from dual union all
select '贾凤梅' as doc_name from dual union all
select '琚泽运' as doc_name from dual union all
select '李宇彤' as doc_name from dual union all
select '李洁' as doc_name from dual union all
select '李斌' as doc_name from dual union all
select '李军伟' as doc_name from dual union all 
select '李鑫' as doc_name from dual union all
select '李雅雯' as doc_name from dual union all 
select '刘秋芬' as doc_name from dual union all 
select '刘琨' as doc_name from dual union all
select '刘亚利' as doc_name from dual union all 
select '刘德新' as doc_name from dual union all 
select '林纪武' as doc_name from dual union all 
select '林颖达' as doc_name from dual union all 
select '雷亦' as doc_name from dual union all
select '吕泉鑫' as doc_name from dual union all 
select '栾涛' as doc_name from dual union all
select '马恒光' as doc_name from dual union all 
select '穆宝敏' as doc_name from dual union all 
select '欧莎' as doc_name from dual union all
select '乔捷' as doc_name from dual union all
select '齐明' as doc_name from dual union all
select '石军' as doc_name from dual union all
select '石瑞娟' as doc_name from dual union all 
select '孙茂峰' as doc_name from dual union all 
select '孙超' as doc_name from dual union all
select '盛杨' as doc_name from dual union all
select '苏放' as doc_name from dual union all
select '田金火' as doc_name from dual union all 
select '唐勇俊' as doc_name from dual union all 
select '唐涛' as doc_name from dual union all
select '陶云云' as doc_name from dual union all 
select '王光清' as doc_name from dual union all 
select '王永兴' as doc_name from dual union all 
select '王兆霖' as doc_name from dual union all 
select '王军' as doc_name from dual union all
select '王峥' as doc_name from dual union all
select '王科冬' as doc_name from dual union all 
select '汪中毓' as doc_name from dual union all 
select '伍忠良' as doc_name from dual union all 
select '吴益军' as doc_name from dual union all 
select '吴小琛' as doc_name from dual union all 
select '徐郦' as doc_name from dual union all
select '徐程鋆' as doc_name from dual union all 
select '谢威' as doc_name from dual union all
select '谢雯' as doc_name from dual union all
select '夏斌斌' as doc_name from dual union all 
select '项彩英' as doc_name from dual union all 
select '尹洁' as doc_name from dual union all
select '游元圆' as doc_name from dual union all 
select '余小群' as doc_name from dual union all 
select '余银华' as doc_name from dual union all 
select '袁涵' as doc_name from dual union all
select '杨海生' as doc_name from dual union all 
select '杨生荣' as doc_name from dual union all 
select '杨伟朝' as doc_name from dual union all 
select '叶贤萍' as doc_name from dual union all 
select '叶文' as doc_name from dual union all
select '于璐冰' as doc_name from dual union all 
select '邹荣' as doc_name from dual union all
select '张媛媛' as doc_name from dual union all 
select '周琳' as doc_name from dual union all
select '张海新' as doc_name from dual union all 
select '张绪光' as doc_name from dual union all 
select '赵建辉' as doc_name from dual union all 
select '章刚' as doc_name from dual union all
select '张钦秋' as doc_name from dual union all 
select '宗岩' as doc_name from dual union all
select '赵颖' as doc_name from dual union all
select '张瑾' as doc_name from dual union all
select '张华辉' as doc_name from dual union all 
select '张吉翔' as doc_name from dual union all 
select '张杰豪' as doc_name from dual union all
select '邓艳芳' as doc_name from dual union all 
select '邓传洲' as doc_name from dual union all 
select '丁启伟' as doc_name from dual union all
select '方祥勇' as doc_name from dual union all
select '范志伟' as doc_name from dual union all
select '葛其泉' as doc_name from dual union all
select '韩炯' as doc_name from dual union all
select '胡建军' as doc_name from dual union all
select '孔晓燕' as doc_name from dual union all
select '李东昕' as doc_name from dual union all
select '吕秋萍' as doc_name from dual union all
select '鲁杰钢' as doc_name from dual union all
select '梁彬' as doc_name from dual union all
select '刘贵彬' as doc_name from dual union all
select '石东骏' as doc_name from dual union all
select '孙勇' as doc_name from dual union all
select '孙业林' as doc_name from dual union all
select '沈佳云' as doc_name from dual union all
select '唐银锋' as doc_name from dual union all
select '王毅' as doc_name from dual union all
select '王卫国' as doc_name from dual union all
select '王冠' as doc_name from dual union all
select '吴翔' as doc_name from dual union all
select '吴晓辉' as doc_name from dual union all
select '解小雨' as doc_name from dual union all
select '徐超玉' as doc_name from dual union all
select '许平文' as doc_name from dual union all
select '叶慧' as doc_name from dual union all
select '杨力生' as doc_name from dual union all
select '周铮文' as doc_name from dual union all
select '张明远' as doc_name from dual union all
select '张军' as doc_name from dual union all
select '胡平生' as doc_name from dual union all
select '安仲任' as doc_name from dual union all 
select '蔡虎' as doc_name from dual union all
select '蔡晓斌' as doc_name from dual union all 
select '陈高威' as doc_name from dual union all 
select '陈微微' as doc_name from dual union all 
select '陈晓华' as doc_name from dual union all 
select '陈晓析' as doc_name from dual union all 
select '陈一' as doc_name from dual union all
select '丁翔' as doc_name from dual union all
select '方任斌' as doc_name from dual union all 
select '傅玉凤' as doc_name from dual union all 
select '高洋洋' as doc_name from dual union all 
select '龚薇' as doc_name from dual union all
select '何希婧' as doc_name from dual union all 
select '何焱' as doc_name from dual union all
select '黄文雯' as doc_name from dual union all 
select '惠淼枫' as doc_name from dual union all 
select '李宝臣' as doc_name from dual union all 
select '李洁' as doc_name from dual union all
select '李鹏飞' as doc_name from dual union all 
select '李伦' as doc_name from dual union all
select '李晴' as doc_name from dual union all
select '栗蓉' as doc_name from dual union all
select '李莘' as doc_name from dual union all
select '李雅雯' as doc_name from dual union all 
select '李毅' as doc_name from dual union all
select '李宇彤' as doc_name from dual union all 
select '梁华' as doc_name from dual union all
select '梁秀国' as doc_name from dual union all 
select '林颖达' as doc_name from dual union all 
select '刘晨曦' as doc_name from dual union all 
select '刘俊岑' as doc_name from dual union all 
select '刘兴财' as doc_name from dual union all 
select '梅刘生' as doc_name from dual union all 
select '孟翔' as doc_name from dual union all
select '孟舒' as doc_name from dual union all
select '欧莎' as doc_name from dual union all
select '彭里程' as doc_name from dual union all 
select '彭红娟' as doc_name from dual union all 
select '乔捷' as doc_name from dual union all
select '乔智' as doc_name from dual union all
select '阮红玲' as doc_name from dual union all 
select '盛杨' as doc_name from dual union all
select '石军' as doc_name from dual union all
select '石瑞娟' as doc_name from dual union all 
select '宋以祯' as doc_name from dual union all 
select '王光清' as doc_name from dual union all 
select '王静静' as doc_name from dual union all 
select '王君凯' as doc_name from dual union all 
select '王恺' as doc_name from dual union all
select '王坤' as doc_name from dual union all
select '魏炜' as doc_name from dual union all
select '吴华' as doc_name from dual union all
select '吴晓栋' as doc_name from dual union all 
select '吴益军' as doc_name from dual union all 
select '项彩英' as doc_name from dual union all 
select '肖亮' as doc_name from dual union all
select '谢威' as doc_name from dual union all
select '徐郦' as doc_name from dual union all
select '徐孟静' as doc_name from dual union all 
select '杨铃珊' as doc_name from dual union all 
select '叶文' as doc_name from dual union all
select '尹洁' as doc_name from dual union all
select '游元圆' as doc_name from dual union all 
select '张弛' as doc_name from dual union all
select '张光晶' as doc_name from dual union all 
select '张海新' as doc_name from dual union all 
select '章剑' as doc_name from dual union all
select '张凌峰' as doc_name from dual union all 
select '张绪光' as doc_name from dual union all 
select '赵建辉' as doc_name from dual union all 
select '赵颖' as doc_name from dual union all
select '郑莫' as doc_name from dual union all
select '周琳' as doc_name from dual union all
select '朱珉' as doc_name from dual union all
select '蔡磊' as doc_name from dual union all
select '曾兴孝' as doc_name from dual union all
select '曾云' as doc_name from dual union all
select '陈丽华' as doc_name from dual union all
select '冯加庆' as doc_name from dual union all
select '龚丽艳' as doc_name from dual union all
select '郝学花' as doc_name from dual union all
select '刘洪光' as doc_name from dual union all
select '潘登' as doc_name from dual union all
select '申顺' as doc_name from dual union all
select '王敏' as doc_name from dual union all
select '王瑞金' as doc_name from dual union all
select '王逸飞' as doc_name from dual union all
select '徐江红' as doc_name from dual union all
select '翁建国' as doc_name from dual union all
select '蔡晓斌' as doc_name from dual union all 
select '蔡庆' as doc_name from dual union all
select '陈斐然' as doc_name from dual union all 
select '陈霖' as doc_name from dual union all
select '陈微微' as doc_name from dual union all 
select '陈晓析' as doc_name from dual union all 
select '戴路' as doc_name from dual union all
select '方任斌' as doc_name from dual union all 
select '干正昱' as doc_name from dual union all 
select '高艳' as doc_name from dual union all
select '龚里' as doc_name from dual union all
select '关长良' as doc_name from dual union all 
select '何嘉勇' as doc_name from dual union all 
select '何书奇' as doc_name from dual union all 
select '何希婧' as doc_name from dual union all 
select '贺洋' as doc_name from dual union all
select '黄实彪' as doc_name from dual union all 
select '黄文雄' as doc_name from dual union all 
select '黄秀聪' as doc_name from dual union all 
select '惠淼枫' as doc_name from dual union all 
select '李洁' as doc_name from dual union all
select '李宇彤' as doc_name from dual union all 
select '李跃博' as doc_name from dual union all 
select '李志杰' as doc_name from dual union all 
select '林纪武' as doc_name from dual union all 
select '刘超洋' as doc_name from dual union all 
select '刘君' as doc_name from dual union all
select '刘亮' as doc_name from dual union all
select '刘秋芬' as doc_name from dual union all 
select '吕泉鑫' as doc_name from dual union all 
select '欧莎' as doc_name from dual union all
select '乔捷' as doc_name from dual union all
select '秦竹林' as doc_name from dual union all 
select '石军' as doc_name from dual union all
select '石瑞娟' as doc_name from dual union all 
select '孙超' as doc_name from dual union all
select '盛杨' as doc_name from dual union all
select '陶云云' as doc_name from dual union all 
select '万玲' as doc_name from dual union all
select '王冰' as doc_name from dual union all
select '王光清' as doc_name from dual union all 
select '王潇斐' as doc_name from dual union all 
select '王峥' as doc_name from dual union all
select '王复启' as doc_name from dual union all 
select '吴华' as doc_name from dual union all
select '吴小琛' as doc_name from dual union all 
select '吴益军' as doc_name from dual union all 
select '项彩英' as doc_name from dual union all 
select '肖美强' as doc_name from dual union all 
select '徐素雯' as doc_name from dual union all 
select '许虓' as doc_name from dual union all
select '徐郦' as doc_name from dual union all
select '谢威' as doc_name from dual union all
select '严智杰' as doc_name from dual union all 
select '杨生荣' as doc_name from dual union all 
select '尹洁' as doc_name from dual union all
select '尹永志' as doc_name from dual union all 
select '余小群' as doc_name from dual union all 
select '袁联海' as doc_name from dual union all 
select '袁盛奇' as doc_name from dual union all 
select '叶文' as doc_name from dual union all
select '游元圆' as doc_name from dual union all 
select '张海燕' as doc_name from dual union all 
select '张钦秋' as doc_name from dual union all 
select '张英娟' as doc_name from dual union all 
select '张绪光' as doc_name from dual union all 
select '赵建辉' as doc_name from dual union all 
select '赵颖' as doc_name from dual union all
select '郑敏' as doc_name from dual union all
select '周琳' as doc_name from dual union all
select '周毅' as doc_name from dual union all
select '周云云' as doc_name from dual union all
select '陈俊敏' as doc_name from dual union all
select '邓士丹' as doc_name from dual union all
select '方晓杰' as doc_name from dual union all
select '房隐' as doc_name from dual union all
select '顾海涛' as doc_name from dual union all
select '郝学花' as doc_name from dual union all
select '何慧明' as doc_name from dual union all
select '贾宗达' as doc_name from dual union all
select '李杰' as doc_name from dual union all
select '李明' as doc_name from dual union all
select '李宁' as doc_name from dual union all
select '林俊' as doc_name from dual union all
select '刘美玉' as doc_name from dual union all
select '毛仁裕' as doc_name from dual union all
select '莫旭巍' as doc_name from dual union all
select '彭春桃' as doc_name from dual union all
select '邱正芳' as doc_name from dual union all
select '全普' as doc_name from dual union all
select '上官胜' as doc_name from dual union all
select '汤明亮' as doc_name from dual union all
select '唐银锋' as doc_name from dual union all
select '汪大联' as doc_name from dual union all
select '王廷富' as doc_name from dual union all
select '王智' as doc_name from dual union all
select '吴旻' as doc_name from dual union all
select '徐长银' as doc_name from dual union all
select '严鸽' as doc_name from dual union all
select '颜学海' as doc_name from dual union all
select '杨凯凯' as doc_name from dual union all
select '尤挺辉' as doc_name from dual union all
select '章海红' as doc_name from dual union all
select '张建华' as doc_name from dual union all
select '张勇' as doc_name from dual union all
select '赵现波' as doc_name from dual )
select t.doc_name, m.cmteeman_name, m.cmteeman_id from t, bibuser.t_flow_meeting_cmteeman m where t.doc_name = m.cmteeman_name(+) and m.cmteeman_type(+) = '5';


--查询t_flow_meeting_cmteeman中的名称在word中是否存在
with t as (
select '夏锦良' as doc_name from dual union all
select '袁玉平' as doc_name from dual union all
select '蔡晓斌' as doc_name from dual union all
select '陈全' as doc_name from dual union all
select '陈微微' as doc_name from dual union all
select '陈霖' as doc_name from dual union all
select '方任斌' as doc_name from dual union all
select '傅玉凤' as doc_name from dual union all
select '郭丽华' as doc_name from dual union all
select '顾文佳' as doc_name from dual union all
select '惠淼枫' as doc_name from dual union all
select '何希婧' as doc_name from dual union all
select '黄实彪' as doc_name from dual union all
select '黄文雯' as doc_name from dual union all
select '贾晓斌' as doc_name from dual union all
select '贾凤梅' as doc_name from dual union all
select '琚泽运' as doc_name from dual union all
select '李宇彤' as doc_name from dual union all
select '李洁' as doc_name from dual union all
select '李斌' as doc_name from dual union all
select '李军伟' as doc_name from dual union all 
select '李鑫' as doc_name from dual union all
select '李雅雯' as doc_name from dual union all 
select '刘秋芬' as doc_name from dual union all 
select '刘琨' as doc_name from dual union all
select '刘亚利' as doc_name from dual union all 
select '刘德新' as doc_name from dual union all 
select '林纪武' as doc_name from dual union all 
select '林颖达' as doc_name from dual union all 
select '雷亦' as doc_name from dual union all
select '吕泉鑫' as doc_name from dual union all 
select '栾涛' as doc_name from dual union all
select '马恒光' as doc_name from dual union all 
select '穆宝敏' as doc_name from dual union all 
select '欧莎' as doc_name from dual union all
select '乔捷' as doc_name from dual union all
select '齐明' as doc_name from dual union all
select '石军' as doc_name from dual union all
select '石瑞娟' as doc_name from dual union all 
select '孙茂峰' as doc_name from dual union all 
select '孙超' as doc_name from dual union all
select '盛杨' as doc_name from dual union all
select '苏放' as doc_name from dual union all
select '田金火' as doc_name from dual union all 
select '唐勇俊' as doc_name from dual union all 
select '唐涛' as doc_name from dual union all
select '陶云云' as doc_name from dual union all 
select '王光清' as doc_name from dual union all 
select '王永兴' as doc_name from dual union all 
select '王兆霖' as doc_name from dual union all 
select '王军' as doc_name from dual union all
select '王峥' as doc_name from dual union all
select '王科冬' as doc_name from dual union all 
select '汪中毓' as doc_name from dual union all 
select '伍忠良' as doc_name from dual union all 
select '吴益军' as doc_name from dual union all 
select '吴小琛' as doc_name from dual union all 
select '徐郦' as doc_name from dual union all
select '徐程鋆' as doc_name from dual union all 
select '谢威' as doc_name from dual union all
select '谢雯' as doc_name from dual union all
select '夏斌斌' as doc_name from dual union all 
select '项彩英' as doc_name from dual union all 
select '尹洁' as doc_name from dual union all
select '游元圆' as doc_name from dual union all 
select '余小群' as doc_name from dual union all 
select '余银华' as doc_name from dual union all 
select '袁涵' as doc_name from dual union all
select '杨海生' as doc_name from dual union all 
select '杨生荣' as doc_name from dual union all 
select '杨伟朝' as doc_name from dual union all 
select '叶贤萍' as doc_name from dual union all 
select '叶文' as doc_name from dual union all
select '于璐冰' as doc_name from dual union all 
select '邹荣' as doc_name from dual union all
select '张媛媛' as doc_name from dual union all 
select '周琳' as doc_name from dual union all
select '张海新' as doc_name from dual union all 
select '张绪光' as doc_name from dual union all 
select '赵建辉' as doc_name from dual union all 
select '章刚' as doc_name from dual union all
select '张钦秋' as doc_name from dual union all 
select '宗岩' as doc_name from dual union all
select '赵颖' as doc_name from dual union all
select '张瑾' as doc_name from dual union all
select '张华辉' as doc_name from dual union all 
select '张吉翔' as doc_name from dual union all 
select '张杰豪' as doc_name from dual union all
select '邓艳芳' as doc_name from dual union all 
select '邓传洲' as doc_name from dual union all 
select '丁启伟' as doc_name from dual union all
select '方祥勇' as doc_name from dual union all
select '范志伟' as doc_name from dual union all
select '葛其泉' as doc_name from dual union all
select '韩炯' as doc_name from dual union all
select '胡建军' as doc_name from dual union all
select '孔晓燕' as doc_name from dual union all
select '李东昕' as doc_name from dual union all
select '吕秋萍' as doc_name from dual union all
select '鲁杰钢' as doc_name from dual union all
select '梁彬' as doc_name from dual union all
select '刘贵彬' as doc_name from dual union all
select '石东骏' as doc_name from dual union all
select '孙勇' as doc_name from dual union all
select '孙业林' as doc_name from dual union all
select '沈佳云' as doc_name from dual union all
select '唐银锋' as doc_name from dual union all
select '王毅' as doc_name from dual union all
select '王卫国' as doc_name from dual union all
select '王冠' as doc_name from dual union all
select '吴翔' as doc_name from dual union all
select '吴晓辉' as doc_name from dual union all
select '解小雨' as doc_name from dual union all
select '徐超玉' as doc_name from dual union all
select '许平文' as doc_name from dual union all
select '叶慧' as doc_name from dual union all
select '杨力生' as doc_name from dual union all
select '周铮文' as doc_name from dual union all
select '张明远' as doc_name from dual union all
select '张军' as doc_name from dual union all
select '胡平生' as doc_name from dual union all
select '安仲任' as doc_name from dual union all 
select '蔡虎' as doc_name from dual union all
select '蔡晓斌' as doc_name from dual union all 
select '陈高威' as doc_name from dual union all 
select '陈微微' as doc_name from dual union all 
select '陈晓华' as doc_name from dual union all 
select '陈晓析' as doc_name from dual union all 
select '陈一' as doc_name from dual union all
select '丁翔' as doc_name from dual union all
select '方任斌' as doc_name from dual union all 
select '傅玉凤' as doc_name from dual union all 
select '高洋洋' as doc_name from dual union all 
select '龚薇' as doc_name from dual union all
select '何希婧' as doc_name from dual union all 
select '何焱' as doc_name from dual union all
select '黄文雯' as doc_name from dual union all 
select '惠淼枫' as doc_name from dual union all 
select '李宝臣' as doc_name from dual union all 
select '李洁' as doc_name from dual union all
select '李鹏飞' as doc_name from dual union all 
select '李伦' as doc_name from dual union all
select '李晴' as doc_name from dual union all
select '栗蓉' as doc_name from dual union all
select '李莘' as doc_name from dual union all
select '李雅雯' as doc_name from dual union all 
select '李毅' as doc_name from dual union all
select '李宇彤' as doc_name from dual union all 
select '梁华' as doc_name from dual union all
select '梁秀国' as doc_name from dual union all 
select '林颖达' as doc_name from dual union all 
select '刘晨曦' as doc_name from dual union all 
select '刘俊岑' as doc_name from dual union all 
select '刘兴财' as doc_name from dual union all 
select '梅刘生' as doc_name from dual union all 
select '孟翔' as doc_name from dual union all
select '孟舒' as doc_name from dual union all
select '欧莎' as doc_name from dual union all
select '彭里程' as doc_name from dual union all 
select '彭红娟' as doc_name from dual union all 
select '乔捷' as doc_name from dual union all
select '乔智' as doc_name from dual union all
select '阮红玲' as doc_name from dual union all 
select '盛杨' as doc_name from dual union all
select '石军' as doc_name from dual union all
select '石瑞娟' as doc_name from dual union all 
select '宋以祯' as doc_name from dual union all 
select '王光清' as doc_name from dual union all 
select '王静静' as doc_name from dual union all 
select '王君凯' as doc_name from dual union all 
select '王恺' as doc_name from dual union all
select '王坤' as doc_name from dual union all
select '魏炜' as doc_name from dual union all
select '吴华' as doc_name from dual union all
select '吴晓栋' as doc_name from dual union all 
select '吴益军' as doc_name from dual union all 
select '项彩英' as doc_name from dual union all 
select '肖亮' as doc_name from dual union all
select '谢威' as doc_name from dual union all
select '徐郦' as doc_name from dual union all
select '徐孟静' as doc_name from dual union all 
select '杨铃珊' as doc_name from dual union all 
select '叶文' as doc_name from dual union all
select '尹洁' as doc_name from dual union all
select '游元圆' as doc_name from dual union all 
select '张弛' as doc_name from dual union all
select '张光晶' as doc_name from dual union all 
select '张海新' as doc_name from dual union all 
select '章剑' as doc_name from dual union all
select '张凌峰' as doc_name from dual union all 
select '张绪光' as doc_name from dual union all 
select '赵建辉' as doc_name from dual union all 
select '赵颖' as doc_name from dual union all
select '郑莫' as doc_name from dual union all
select '周琳' as doc_name from dual union all
select '朱珉' as doc_name from dual union all
select '蔡磊' as doc_name from dual union all
select '曾兴孝' as doc_name from dual union all
select '曾云' as doc_name from dual union all
select '陈丽华' as doc_name from dual union all
select '冯加庆' as doc_name from dual union all
select '龚丽艳' as doc_name from dual union all
select '郝学花' as doc_name from dual union all
select '刘洪光' as doc_name from dual union all
select '潘登' as doc_name from dual union all
select '申顺' as doc_name from dual union all
select '王敏' as doc_name from dual union all
select '王瑞金' as doc_name from dual union all
select '王逸飞' as doc_name from dual union all
select '徐江红' as doc_name from dual union all
select '翁建国' as doc_name from dual union all
select '蔡晓斌' as doc_name from dual union all 
select '蔡庆' as doc_name from dual union all
select '陈斐然' as doc_name from dual union all 
select '陈霖' as doc_name from dual union all
select '陈微微' as doc_name from dual union all 
select '陈晓析' as doc_name from dual union all 
select '戴路' as doc_name from dual union all
select '方任斌' as doc_name from dual union all 
select '干正昱' as doc_name from dual union all 
select '高艳' as doc_name from dual union all
select '龚里' as doc_name from dual union all
select '关长良' as doc_name from dual union all 
select '何嘉勇' as doc_name from dual union all 
select '何书奇' as doc_name from dual union all 
select '何希婧' as doc_name from dual union all 
select '贺洋' as doc_name from dual union all
select '黄实彪' as doc_name from dual union all 
select '黄文雄' as doc_name from dual union all 
select '黄秀聪' as doc_name from dual union all 
select '惠淼枫' as doc_name from dual union all 
select '李洁' as doc_name from dual union all
select '李宇彤' as doc_name from dual union all 
select '李跃博' as doc_name from dual union all 
select '李志杰' as doc_name from dual union all 
select '林纪武' as doc_name from dual union all 
select '刘超洋' as doc_name from dual union all 
select '刘君' as doc_name from dual union all
select '刘亮' as doc_name from dual union all
select '刘秋芬' as doc_name from dual union all 
select '吕泉鑫' as doc_name from dual union all 
select '欧莎' as doc_name from dual union all
select '乔捷' as doc_name from dual union all
select '秦竹林' as doc_name from dual union all 
select '石军' as doc_name from dual union all
select '石瑞娟' as doc_name from dual union all 
select '孙超' as doc_name from dual union all
select '盛杨' as doc_name from dual union all
select '陶云云' as doc_name from dual union all 
select '万玲' as doc_name from dual union all
select '王冰' as doc_name from dual union all
select '王光清' as doc_name from dual union all 
select '王潇斐' as doc_name from dual union all 
select '王峥' as doc_name from dual union all
select '王复启' as doc_name from dual union all 
select '吴华' as doc_name from dual union all
select '吴小琛' as doc_name from dual union all 
select '吴益军' as doc_name from dual union all 
select '项彩英' as doc_name from dual union all 
select '肖美强' as doc_name from dual union all 
select '徐素雯' as doc_name from dual union all 
select '许虓' as doc_name from dual union all
select '徐郦' as doc_name from dual union all
select '谢威' as doc_name from dual union all
select '严智杰' as doc_name from dual union all 
select '杨生荣' as doc_name from dual union all 
select '尹洁' as doc_name from dual union all
select '尹永志' as doc_name from dual union all 
select '余小群' as doc_name from dual union all 
select '袁联海' as doc_name from dual union all 
select '袁盛奇' as doc_name from dual union all 
select '叶文' as doc_name from dual union all
select '游元圆' as doc_name from dual union all 
select '张海燕' as doc_name from dual union all 
select '张钦秋' as doc_name from dual union all 
select '张英娟' as doc_name from dual union all 
select '张绪光' as doc_name from dual union all 
select '赵建辉' as doc_name from dual union all 
select '赵颖' as doc_name from dual union all
select '郑敏' as doc_name from dual union all
select '周琳' as doc_name from dual union all
select '周毅' as doc_name from dual union all
select '周云云' as doc_name from dual union all
select '陈俊敏' as doc_name from dual union all
select '邓士丹' as doc_name from dual union all
select '方晓杰' as doc_name from dual union all
select '房隐' as doc_name from dual union all
select '顾海涛' as doc_name from dual union all
select '郝学花' as doc_name from dual union all
select '何慧明' as doc_name from dual union all
select '贾宗达' as doc_name from dual union all
select '李杰' as doc_name from dual union all
select '李明' as doc_name from dual union all
select '李宁' as doc_name from dual union all
select '林俊' as doc_name from dual union all
select '刘美玉' as doc_name from dual union all
select '毛仁裕' as doc_name from dual union all
select '莫旭巍' as doc_name from dual union all
select '彭春桃' as doc_name from dual union all
select '邱正芳' as doc_name from dual union all
select '全普' as doc_name from dual union all
select '上官胜' as doc_name from dual union all
select '汤明亮' as doc_name from dual union all
select '唐银锋' as doc_name from dual union all
select '汪大联' as doc_name from dual union all
select '王廷富' as doc_name from dual union all
select '王智' as doc_name from dual union all
select '吴旻' as doc_name from dual union all
select '徐长银' as doc_name from dual union all
select '严鸽' as doc_name from dual union all
select '颜学海' as doc_name from dual union all
select '杨凯凯' as doc_name from dual union all
select '尤挺辉' as doc_name from dual union all
select '章海红' as doc_name from dual union all
select '张建华' as doc_name from dual union all
select '张勇' as doc_name from dual union all
select '赵现波' as doc_name from dual)
select t.doc_name, m.cmteeman_name, m.cmteeman_id from t, bibuser.t_flow_meeting_cmteeman m where t.doc_name(+) = m.cmteeman_name and m.cmteeman_type = '5';


2、插入和更新
select * from bibuser.t_flow_meeting_cmteeman c where c.cmteeman_name like '安仲任';
select * from OUSER.T_XTGL_USER u where u.user_id=3751;   
select * from OUSER.T_XTGL_USER u where u.user_name like '张弛';  --查cmteeman_userid
select * from ouser.t_xtgl_organization f where f.organization_id=27896; --查belong_org_id
select max(c.cmteeman_id+1) from bibuser.t_flow_meeting_cmteeman c;  --查cmteeman_id

--内核委员会表t_flow_meeting_cmteeman中不存在的委员，在word中存在，将该委员插入表中
insert into bibuser.t_flow_meeting_cmteeman (CMTEEMAN_ID, CMTEEMAN_NAME, CMTEEMAN_ATTR, EMAIL, CMTEEMAN_SOURCE, BELONG_ORG_ID, CMTEEMAN_USERID, CMTEEMAN_TYPE, EXTERNAL_ORG, CREATE_USERID, CREATE_TIME, REC_STATUS, UPDATE_TIME)
select 5134669, '杨伟朝', '股权业务内核委员委员', null, '1', 190, 9927, '5', '', 0, sysdate, null, null from dual;
insert into bibuser.t_flow_meeting_cmteeman (CMTEEMAN_ID, CMTEEMAN_NAME, CMTEEMAN_ATTR, EMAIL, CMTEEMAN_SOURCE, BELONG_ORG_ID, CMTEEMAN_USERID, CMTEEMAN_TYPE, EXTERNAL_ORG, CREATE_USERID, CREATE_TIME, REC_STATUS, UPDATE_TIME)
select 5134670, '刘德新', '股权业务内核委员委员', null, '1', 190, 2611, '5', '', 0, sysdate, null, null from dual;
insert into bibuser.t_flow_meeting_cmteeman (CMTEEMAN_ID, CMTEEMAN_NAME, CMTEEMAN_ATTR, EMAIL, CMTEEMAN_SOURCE, BELONG_ORG_ID, CMTEEMAN_USERID, CMTEEMAN_TYPE, EXTERNAL_ORG, CREATE_USERID, CREATE_TIME, REC_STATUS, UPDATE_TIME)
select 5134671, '章剑', '债券业务内核委员委员',null, '1', 105, 5261, '5', '', 0, sysdate, null, null from dual;
insert into bibuser.t_flow_meeting_cmteeman (CMTEEMAN_ID, CMTEEMAN_NAME, CMTEEMAN_ATTR, EMAIL, CMTEEMAN_SOURCE, BELONG_ORG_ID, CMTEEMAN_USERID, CMTEEMAN_TYPE, EXTERNAL_ORG, CREATE_USERID, CREATE_TIME, REC_STATUS, UPDATE_TIME)
select 5134672, '齐明', '股权业务内核委员委员', null, '1', 190, 9925, '5', '', 0, sysdate, null, null from dual;
insert into bibuser.t_flow_meeting_cmteeman (CMTEEMAN_ID, CMTEEMAN_NAME, CMTEEMAN_ATTR, EMAIL, CMTEEMAN_SOURCE, BELONG_ORG_ID, CMTEEMAN_USERID, CMTEEMAN_TYPE, EXTERNAL_ORG, CREATE_USERID, CREATE_TIME, REC_STATUS, UPDATE_TIME)
select 5134673, '徐程鋆', '股权业务内核委员委员', null, '1', 190, 23072, '5', '', 0, sysdate, null, null from dual;
insert into bibuser.t_flow_meeting_cmteeman (CMTEEMAN_ID, CMTEEMAN_NAME, CMTEEMAN_ATTR, EMAIL, CMTEEMAN_SOURCE, BELONG_ORG_ID, CMTEEMAN_USERID, CMTEEMAN_TYPE, EXTERNAL_ORG, CREATE_USERID, CREATE_TIME, REC_STATUS, UPDATE_TIME)
select 5134674, '孟舒', '债券业务内核委员委员',null, '1', 105, 17557, '5', '', 0, sysdate, null, null from dual;
insert into bibuser.t_flow_meeting_cmteeman (CMTEEMAN_ID, CMTEEMAN_NAME, CMTEEMAN_ATTR, EMAIL, CMTEEMAN_SOURCE, BELONG_ORG_ID, CMTEEMAN_USERID, CMTEEMAN_TYPE, EXTERNAL_ORG, CREATE_USERID, CREATE_TIME, REC_STATUS, UPDATE_TIME)
select 5134675, '谢雯', '股权业务内核委员委员', null, '1', 190, 2605, '5', '', 0, sysdate, null, null from dual;
insert into bibuser.t_flow_meeting_cmteeman (CMTEEMAN_ID, CMTEEMAN_NAME, CMTEEMAN_ATTR, EMAIL, CMTEEMAN_SOURCE, BELONG_ORG_ID, CMTEEMAN_USERID, CMTEEMAN_TYPE, EXTERNAL_ORG, CREATE_USERID, CREATE_TIME, REC_STATUS, UPDATE_TIME)
select 5134676, '王科冬', '股权业务内核委员委员', null, '1', 190, 22194, '5', '', 0, sysdate, null, null from dual;
insert into bibuser.t_flow_meeting_cmteeman (CMTEEMAN_ID, CMTEEMAN_NAME, CMTEEMAN_ATTR, EMAIL, CMTEEMAN_SOURCE, BELONG_ORG_ID, CMTEEMAN_USERID, CMTEEMAN_TYPE, EXTERNAL_ORG, CREATE_USERID, CREATE_TIME, REC_STATUS, UPDATE_TIME)
select 5134677, '张弛', '债券业务内核委员委员',null, '1', 105, 6041, '5', '', 0, sysdate, null, null from dual;
commit；

--内核委员会表t_flow_meeting_cmteeman中存在的委员，在word中不存在，将rec_status置为-1
update bibuser.t_flow_meeting_cmteeman c set c.rec_status=-1 where c.cmteeman_name like '潘光明';
update bibuser.t_flow_meeting_cmteeman c set c.rec_status=-1 where c.cmteeman_name like '赵新征';
update bibuser.t_flow_meeting_cmteeman c set c.rec_status=-1 where c.cmteeman_name like '薛波'  ;
update bibuser.t_flow_meeting_cmteeman c set c.rec_status=-1 where c.cmteeman_name like '李爱妍';
update bibuser.t_flow_meeting_cmteeman c set c.rec_status=-1 where c.cmteeman_name like '李勇'  ;
update bibuser.t_flow_meeting_cmteeman c set c.rec_status=-1 where c.cmteeman_name like '魏韫新';
update bibuser.t_flow_meeting_cmteeman c set c.rec_status=-1 where c.cmteeman_name like '周华'  ;
update bibuser.t_flow_meeting_cmteeman c set c.rec_status=-1 where c.cmteeman_name like '徐柯'  ;
update bibuser.t_flow_meeting_cmteeman c set c.rec_status=-1 where c.cmteeman_name like '马学韬';
update bibuser.t_flow_meeting_cmteeman c set c.rec_status=-1 where c.cmteeman_name like '徐礼敏';
update bibuser.t_flow_meeting_cmteeman c set c.rec_status=-1 where c.cmteeman_name like '刘智'  ;
update bibuser.t_flow_meeting_cmteeman c set c.rec_status=-1 where c.cmteeman_name like '吴志平';